name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 4 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Find HMC version'
        run: echo "HMC_VERSION=$(cat Dockerfile | grep -oP 'HMC_VERSION=\"(\K[0-9\.]+)')" >> $GITHUB_ENV

      - name: 'Registry login'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Activate Java 8'
        run: sed -Ei "s/temurin-[0-9]{1,2}-jre/temurin-8-jre/" Dockerfile
      - name: 'Build and publish Java 8 image'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.HMC_VERSION }}-java8

      - name: 'Activate Java 11'
        run: sed -Ei "s/temurin-[0-9]{1,2}-jre/temurin-11-jre/" Dockerfile
      - name: 'Build and publish Java 11 image'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.HMC_VERSION }}-java11

      - name: 'Activate Java 17'
        run: sed -Ei "s/temurin-[0-9]{1,2}-jre/temurin-17-jre/" Dockerfile
      - name: 'Build and publish Java 17 image'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.HMC_VERSION }}-java17

      - name: 'Activate Java 21'
        run: sed -Ei "s/temurin-[0-9]{1,2}-jre/temurin-21-jre/" Dockerfile
      - name: 'Build and publish Java 21 image'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.HMC_VERSION }}-java21
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.HMC_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:latest
