name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 4 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Find HMC version'
        run: echo "HMC_VERSION=$(cat Dockerfile | grep -oP 'HMC_VERSION=\"(\K[0-9\.]+)')" >> $GITHUB_ENV

      - name: 'Registry login'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and publish image'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.HMC_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:latest
