name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 4 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Trivy scan'
        uses: aquasecurity/trivy-action@0.12.0
        id: trivy-fs
        with:
          scan-type: 'fs'
          scanners: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy.sarif'
          exit-code: 1

      - name: 'Trivy report'
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure() # run if prior action was not cancelled or skipped
        with:
          sarif_file: 'trivy.sarif'

      - name: 'Find HMC version'
        run: echo "HMC_VERSION=$(cat Dockerfile | grep -oP 'HMC_VERSION=\"(\K[0-9\.]+)')" >> $GITHUB_ENV

      - name: 'Registry login'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and publish image'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/headlessmc:${{ env.headlessmc_VERSION }}
